updated hello.md
rhdevs/intro_to_git pull request #19
Opened 2021-09-13 17:58 UTC by eugenetaan

2021-09-14 00:47 UTC, rldefa commented
merge conflict

2021-09-14 17:42 UTC, eugenetaan commented
Resolved Conflicts

2021-09-15 02:59 UTC, rldefa requested changes

2021-09-15 02:59 UTC, rldefa commented on hello.md
> +<<<<<<< HEAD
Remove all these that were added in by Git.

2021-09-15 02:59 UTC, rldefa commented on hello.md
> +=======
same for this line

2021-09-15 03:00 UTC, rldefa commented
Also, you are supposed to keep the one you wrote yourself not the one in submit.md

2021-09-15 03:40 UTC, eugenetaan commented
Edited to my own one and removed git changes

2021-09-15 04:46 UTC, rldefa commented
lgtm

2021-09-15 04:46 UTC, closed without merging

2021-09-15 04:47 UTC, rldefa commented
Except for the fact u updated hello.md on github please don't make that a habit. Apart from that alls good

2021-09-15 04:47 UTC, rldefa commented
Close one eye for now but DONT do everything on github.